In [1]:
#Nomor 1
#Deklarasi numpy array kosong berukuran 2 x 3, beri array tersebut nama array1
import numpy as np
array1 = np.empty([2,3], dtype = int)
print(array1)

[[775364699 858993459 858993459]
 [807411756 538981422 538976288]]


In [2]:
#Nomor 2
#Deklarasi numpy array berisi angka 0, berukuran 100 x 150, beri array tersebut nama array2
array2 = np.zeros([100,150])
print(array2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
#Nomor 3
#Deklarasi numpy array berisi angka 1, berukuran 150 x 100, beri array tersebut nama array3
array3 = np.ones([150,100])
print(array3)  

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [4]:
#Nomor 4
#Cari type data dari array1, array2, dan array3
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int32
float64
float64


In [5]:
#Nomor 5
#Cari ukuran (shape) dari array 2
print(array2.shape)

(100, 150)


In [6]:
#Nomor 6
#Putar array3 sehingga menjadi berukuran 100 x 150
array3T = np.transpose(array3)
print(array3T)
print(array3T.shape)


[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
(100, 150)


In [7]:
#Nomor 7
#Satukan array2 dan array3 menjadi sebuah array berukuran 100 x 300, beri array tersebut nama array4
array4 = np.concatenate((array2, array3T), axis=1)
print(array4)
print(array4.shape)


[[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
(100, 300)


In [8]:
#Nomor 8
#Deklarasikan sebuah array kososng berukuran 5 x 7, beri nama array5. Array dipersiapkan untuk menyimpan nilai-nilai bertype float
array5 = np.empty([5,7], dtype=float)
print(array5)

[[8.63481609e-312 8.63481264e-312 0.00000000e+000 0.00000000e+000
  1.42413554e-306 1.16095484e-028 1.67647110e+243]
 [2.18482268e+209 1.92693517e+161 6.37228148e+194 1.05781533e+208
  4.72322002e+164 5.04533665e+223 1.05219807e-153]
 [7.69110585e+218 4.23978203e-051 3.02876088e-152 1.78908897e+161
  6.97816131e+252 1.21664701e+200 1.71220755e+214]
 [4.16775458e+199 4.27255729e+180 4.11423850e+223 2.87927608e-014
  7.52736939e+252 5.47110405e-095 3.12269278e+184]
 [3.77075688e+233 1.96087885e+243 2.59027849e-144 4.82412328e+228
  1.04718130e-142 1.94920677e-153 1.58372743e-319]]


In [9]:
#Nomor 9
#Gunakan loop (for atau while) untuk mem-printout (display) setiap baris dari array2
print("Menggunakan loop for")
for i in array2:
    print(i)

print("Menggunakan loop while")
i = 0
while i < len(array2):
    print(array2[i])
    i += 1


Menggunakan loop for
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [10]:
#Nomor 10
#Gunakan array1 untuk menunjukkan perbedaan bila melakukan shallow copy dan deep copy

#Shallow Copy
shallow = array1.view()
print(shallow)

#Deep Copy
deep = array1.copy()
print(deep)

array1[0][0] = 1   
print(array1[0][0])
print(shallow[0][0])
print(deep[0][0])

[[775364699 858993459 858993459]
 [807411756 538981422 538976288]]
[[775364699 858993459 858993459]
 [807411756 538981422 538976288]]
1
1
775364699
